# Generated by Django 5.2.11 on 2026-02-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام استاد')),
                ('expertise', models.CharField(max_length=255, verbose_name='تخصص')),
                ('bio', models.TextField(verbose_name='بیوگرافی و رزومه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='تصویر')),
                ('courses_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دوره\u200cها')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان رویداد')),
                ('start_datetime', models.DateTimeField(verbose_name='تاریخ و ساعت شروع دقیق')),
                ('date_display', models.CharField(max_length=50, verbose_name='متن تاریخ (نمایشی)')),
                ('time_display', models.CharField(max_length=50, verbose_name='متن ساعت (نمایشی)')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='آیا مجازی است؟')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مکان برگزاری / پلتفرم')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='لینک جلسه (فقط مجازی)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='ظرفیت کل')),
                ('registered_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ثبت\u200cنامی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='تصویر بنر')),
                ('description', models.TextField(verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category', verbose_name='دسته\u200cبندی')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.instructor', verbose_name='مدرس')),
            ],
        ),
    ]
