# Generated by Django 5.2.11 on 2026-02-07 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=20, unique=True, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('paid', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداختی')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('is_present', models.BooleanField(default=False, verbose_name='وضعیت حضور')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event', verbose_name='رویداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
